"""campo senha

Revision ID: 73af66e341e0
Revises: b6d0c5c30240
Create Date: 2024-09-16 19:50:16.274889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73af66e341e0'
down_revision = 'b6d0c5c30240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('senha')

    # ### end Alembic commands ###
